"""Generate an importable ISTQB CT-AI question bank.
The bank uses 7 chapter-specific lenses over 34 distinct, domain-grounded cases.
Each case has a different learning point, scenario, and decision task; it is not
created by changing a number in a copied question.
"""
from pathlib import Path
from pprint import pprint

# Each tuple is: concept, domain, concrete situation, expected decision focus.
CASES = [
("AI versus conventional automation", "railway signalling", "A rules engine rejects a route when one fixed track circuit is occupied, while a learned detector estimates whether a camera image contains debris.", "contrast explicit deterministic logic with learned inference and identify the appropriate assurance evidence"),
("narrow AI", "radiology", "A chest-imaging model can flag pneumothorax but cannot schedule patients, interpret blood chemistry, or explain unrelated symptoms.", "define the operational boundary and prevent unsupported claims about general intelligence"),
("general AI claims", "warehouse robotics", "A vendor says a picking model trained on parcels will reason safely about forklifts, cold storage, and novel human gestures.", "challenge the transfer claim and specify evidence needed outside the training task"),
("generative and discriminative models", "insurance claims", "A classifier assigns a fraud probability to a claim, whereas a language model drafts a loss narrative from adjuster notes.", "distinguish prediction of labels from generation of new sequences and test the different failure modes"),
("explainability", "credit lending", "A lender must give an applicant a meaningful reason for an adverse decision rather than only expose a neural-network confidence score.", "select an explanation suitable for the affected user and the regulatory purpose"),
("local versus global interpretability", "water treatment", "Operators need to know why today's chlorine alert fired and also which variables generally drive the plant's risk model.", "separate a case explanation from a population-level model explanation"),
("adaptability", "online advertising", "A ranking service updates from clicks hourly, creating a possibility that a short-lived bot campaign changes future recommendations.", "control online learning, bound updates, and detect harmful feedback loops"),
("frontier AI", "drug discovery", "A foundation model proposes molecules and uses tools to search papers and call a synthesis planner that were absent from its original training.", "identify capability, autonomy, and evaluation risks introduced by the new system composition"),
("quality characteristics", "mobile banking", "A release is fast and accurate in the lab but consumes excessive battery and fails when connectivity is intermittent.", "balance functional suitability, performance efficiency, reliability, and usability"),
("black-box risk", "aviation maintenance", "A defect predictor recommends replacing a turbine part, but engineers cannot reconstruct which sensor evidence triggered the recommendation.", "define traceability, human review, and fallback controls before operational use"),
("AI hardware", "autonomous vehicle", "A perception model passes on a desktop GPU but misses pedestrians when quantized on the vehicle's safety-certified accelerator.", "test hardware-dependent numerical behavior, latency, and safety margins"),
("regulatory obligations", "public-sector benefits", "An automated eligibility service affects access to housing support and processes identity and income data from several agencies.", "map impact assessment, transparency, human oversight, and data-protection obligations"),
("fairness", "recruitment", "Historical hiring data contains fewer successful applications from a protected group because an earlier screening policy excluded them.", "recognize proxy discrimination and choose appropriate fairness and data-remediation checks"),
("validation versus testing", "medical triage", "A model scores well on a held-out hospital dataset, but clinicians have not confirmed that its output supports safe triage decisions.", "distinguish whether the system solves the intended clinical problem from whether it is defect-free"),
("data drift", "e-commerce", "The product catalogue changes seasonally and the relationship between price, promotion, and returns shifts after a new delivery policy.", "detect feature and concept drift and decide when retraining or review is justified"),
("deterministic versus probabilistic behavior", "fraud detection", "Repeated submissions with identical fields produce slightly different rankings after a model-serving cluster is upgraded.", "investigate randomness, nondeterminism, reproducibility, and the correct oracle"),
("transfer learning", "agriculture", "A crop-disease classifier trained on clear smartphone photographs is adapted to infrared images from greenhouse sensors.", "assess what knowledge transfers, what must be fine-tuned, and which new cases need labels"),
("supervised learning", "manufacturing", "Thousands of labelled weld images identify cracks, but the labels were made by one inspector using an undocumented standard.", "evaluate label quality, class coverage, and the risks of learning annotator bias"),
("unsupervised learning", "cybersecurity", "An anomaly detector groups login events without incident labels and produces a cluster that analysts believe represents credential stuffing.", "assess cluster stability, meaningfulness, and the analyst's role in assigning semantics"),
("feature engineering", "energy forecasting", "A demand model uses raw timestamps, temperature, holidays, and a rolling consumption measure that may accidentally include future readings.", "design leakage-safe features and check whether representations reflect the physical process"),
("hyperparameter tuning", "speech recognition", "A team repeatedly selects architecture depth and learning rate using the production test set until word error decreases.", "explain test-set contamination and establish a nested or otherwise independent selection process"),
("cross-validation", "small business credit", "Only 420 labelled loans are available and several loans belong to the same customer or corporate group.", "choose grouped or stratified folds and prevent related records crossing train and validation boundaries"),
("model evaluation", "traffic prediction", "Average error is low because most roads are quiet, yet the model is consistently late during rare evacuation surges.", "select segment, tail, and event-based metrics rather than relying on one aggregate score"),
("risk-based testing", "industrial control", "A false negative could overheat a chemical reactor, while a false positive merely pauses production for inspection.", "prioritize tests, thresholds, and independent controls according to harm and likelihood"),
("data quality", "national language service", "A translation corpus contains duplicated sentences, inconsistent Unicode, missing dialect tags, and machine-translated references.", "profile defects, define acceptance criteria, and estimate their effect on evaluation"),
("governance", "hospital procurement", "A third-party vendor updates a diagnostic model without notifying the hospital or supplying a new validation report.", "establish ownership, change control, audit evidence, and release gates"),
("privacy and memorization", "customer support", "A generative assistant reproduces a customer's phone number when prompted with an apparently unrelated conversation fragment.", "test memorization and disclosure resistance while preserving useful support behavior"),
("robustness", "facial access control", "The camera is exposed to glare, masks, seasonal clothing, and a printed photograph designed to fool the recognizer.", "build perturbation, presentation-attack, and environmental robustness tests"),
("uncertainty", "seismic monitoring", "An earthquake classifier is highly confident on familiar stations but gives no confidence warning for a new sensor type.", "calibrate uncertainty, detect out-of-distribution inputs, and define abstention behavior"),
("human oversight", "content moderation", "A classifier removes a journalist's documentary image and an appeal queue is already overloaded.", "design meaningful review, escalation, and workload-aware override controls"),
("reproducibility", "weather forecasting", "The same training commit yields a different model because data snapshots, random seeds, and preprocessing containers were not recorded.", "identify provenance requirements and make a rerun independently verifiable"),
("security and poisoning", "smart-grid forecasting", "An attacker inserts plausible but strategically timed meter readings to influence a model used for load balancing.", "identify poisoning indicators, resilience controls, and safe operational fallback"),
("model monitoring", "last-mile delivery", "Accuracy appears stable overall, but performance for rural addresses falls after a new mapping provider changes geocoding.", "define slice-based monitoring, alert thresholds, diagnosis, and remediation"),
("lifecycle decommissioning", "school tutoring", "A tutoring model is retired after curriculum standards change, but old recommendations remain in exported teacher reports.", "control archival, deletion, communication, and residual-risk management"),
]

CHAPTERS = {
1: ("AI foundations and applications", [
"A port authority is deciding whether to use a fixed rule table or a learned vision model to identify containers.", "A hospital advertises an appointment bot as intelligent even though it only follows a dialogue tree.", "A mining company evaluates a model trained on one ore type for a different geological region.", "A game studio compares a text generator with a sentiment classifier for player feedback.", "A court service needs reasons for a document-routing decision.", "A factory wants both an explanation of one alarm and a summary of overall model behavior.", "A music recommender learns from each listener's skips during a live concert.", "A research lab gives a foundation model access to external tools and laboratory robots.", "A food-delivery app meets accuracy targets but times out on low-end phones.", "A nuclear maintenance team receives a prediction with no evidence trail.", "A drone model behaves differently on an edge chip than in the cloud.", "A city uses an algorithm to allocate emergency accommodation.", "A university admissions model inherits imbalance from historical applications.", "A nurse questions whether a validated score actually measures clinical usefulness.", "A streaming service sees changed viewer behavior after a pricing redesign.", "A payment model is sensitive to thread scheduling after deployment.", "A vineyard transfers a classifier from RGB images to multispectral imagery.", "A weld dataset is labelled by inspectors with conflicting standards.", "A security team clusters events without ground-truth labels.", "A power operator engineers calendar and weather features for demand.", "A speech team tunes parameters against its final benchmark.", "A lender has few records and repeated borrowers.", "A city forecast hides failures during festivals behind a good average.", "A refinery assigns testing effort according to safety consequences.", "A multilingual corpus has duplicates and inconsistent scripts.", "A hospital cannot govern an externally updated model.", "A chatbot leaks a private appointment detail.", "A door camera faces weather and spoofing attempts.", "A flood sensor sees a new measurement regime.", "A moderation team cannot review every automated removal.", "A forecasting run cannot be recreated from source control.", "A grid model is targeted with poisoned measurements.", "A logistics model degrades only in remote postcodes.", "A school archives obsolete recommendations without a retention plan."]),
2: ("Data and learning", [
"A retailer labels product photos using three incompatible descriptions of colour.", "A clinic has abundant unlabeled scans but only a small set reviewed by specialists.", "A bank's positive fraud cases are less than one percent of transactions.", "A factory sensor records values at different sampling rates after a firmware change.", "A farm model receives soil measurements with systematic gaps in dry fields.", "A call-centre corpus contains accents absent from the development sample.", "A credit dataset includes an account identifier that nearly reveals the target.", "A transit model is trained on routes that were later redesigned.", "A museum uses transfer learning from natural images for infrared artefacts.", "A retailer's validation set contains multiple photographs of the same object.", "A hospital tunes a threshold separately for each ward.", "A weather dataset has a sudden change caused by a new satellite.", "A cyber anomaly cluster is split differently on every run.", "A recommender learns from clicks generated by its previous recommendations.", "A manufacturing label is corrected after a machine calibration audit.", "A language model corpus includes copyrighted private messages.", "A loan model under-represents self-employed applicants.", "A sensor pipeline silently converts missing values to zero.", "A navigation model sees a new road surface after resurfacing.", "A speech model's rare language has no dedicated test partition.", "A medical image is horizontally flipped during augmentation although laterality matters.", "A crop model uses harvest outcome data accidentally available at prediction time.", "A delivery dataset contains duplicate orders from retry logic.", "A safety model has many normal examples but few near-misses.", "A catalogue taxonomy changes between training and production.", "A model learns hospital-specific scanner artefacts rather than disease signs.", "A fraud team selects features after inspecting the held-out results.", "A clustering analyst names groups before checking their stability.", "A demand model has temporal dependence across train and validation.", "A robot dataset records only successful grasps.", "A call classifier's label policy changes halfway through collection.", "A satellite archive has different geographic coverage by season.", "A model's calibration is checked only on the overall population.", "A training pipeline has no record of the data snapshot used."]),
3: ("AI quality and model evaluation", [
"A banking classifier has strong ROC-AUC but poor precision at the operational threshold.", "A medical detector misses rare but dangerous findings.", "A translation system is fluent but changes medication dosage numbers.", "A warehouse robot is accurate but exceeds its response-time budget.", "An insurance model performs well overall but poorly for new policyholders.", "A turbine predictor gives unstable results near the maintenance boundary.", "A speech assistant works in a quiet lab but fails beside industrial machinery.", "A generative report tool invents citations that look plausible.", "A recommendation model is accurate but reinforces a narrow content bubble.", "A vision model's confidence is not aligned with observed correctness.", "A water model has a high average score but misses regulatory exceedances.", "A classifier behaves differently after compiler optimisation.", "A fraud detector's threshold causes unacceptable manual-review volume.", "A credit model's errors differ by region and income band.", "A robot planner has no safe output for an unseen obstacle.", "A medical triage model changes output when irrelevant pixels are altered.", "A weather model is evaluated only on mild conditions.", "A product-search model returns relevant results but violates latency SLOs.", "A road classifier is tested only in daylight.", "A legal summarizer omits qualifying exceptions.", "A smart-meter model has uncertain predictions on newly connected homes.", "A text generator repeats training phrases verbatim.", "A diagnosis model is validated at one hospital only.", "A customer model overfits a seasonal promotion.", "A vision model's explanation highlights a hospital logo.", "A safety controller's false-positive cost differs from false-negative cost.", "A model passes unit tests while the data pipeline swaps two columns.", "A recommender's offline gain disappears in an online experiment.", "A defect model is evaluated with labels delayed by three months.", "A classifier has excellent mean accuracy but one class is never predicted.", "A chatbot's refusal behavior is inconsistent across paraphrases.", "A model is retrained weekly with no regression suite.", "A plant detector is accurate only for one camera vendor.", "An evaluator cannot tell whether a failure came from data or code."]),
4: ("AI-specific testing techniques", [
"A medical classifier is tested with metamorphic changes that should preserve diagnosis.", "A road-sign recognizer receives rotated and partially occluded images.", "A chatbot is probed with adversarial instructions embedded in retrieved documents.", "A recommender is checked for invariant results when item IDs are renamed.", "A fraud model is challenged with synthetic borderline transactions.", "A speech recognizer is tested across accents, microphones, and background noise.", "A generative assistant is tested for prompt injection through a support ticket.", "A robot perception stack is tested with sensor dropout and delayed frames.", "A credit model's explanation is compared with its actual feature sensitivity.", "A forecasting service is tested after a timezone and daylight-saving transition.", "A document model encounters rotated pages and unreadable fonts.", "A classifier receives out-of-distribution images from a different camera.", "A safety model is tested with rare combinations of individually normal inputs.", "A model is rerun with controlled seeds to separate variance from defects.", "A training pipeline is tested against label permutation as a sanity check.", "A ranking system is checked for position bias in its feedback loop.", "A model API is tested for schema drift and missing optional fields.", "A detector is tested when a protected attribute is changed while content stays fixed.", "A generative model is checked for unsafe completion and useful refusal.", "A time-series model is tested at the beginning and end of daylight-saving weeks.", "A medical model is tested with images from a new scanner manufacturer.", "A classifier is tested for sensitivity to compression artefacts.", "A data loader is tested with duplicate records and empty partitions.", "A model is tested after quantization to lower numerical precision.", "A retrieval system is tested when the knowledge base contains conflicting versions.", "An anomaly detector is tested on injected but realistic attack traces.", "A production monitor is tested by replaying a known drift episode.", "A human override path is tested under queue overload.", "A model is tested for deterministic results across inference replicas.", "A benchmark is tested for leakage from training documents.", "A multi-label model is tested when labels are correlated but one is absent.", "A model update is tested for backward compatibility with old clients.", "A vision model is tested against adversarial stickers on objects.", "An evaluation harness is tested with a deliberately broken oracle."]),
5: ("Governance, risk, and responsible AI", [
"A municipality deploys a model to prioritize inspections of rental properties.", "A hospital uses an external foundation model to draft discharge summaries.", "An employer screens applicants using a vendor's opaque ranking service.", "A bank must retain evidence for decisions made by an automated credit workflow.", "A school uses face analysis to mark attendance despite unequal camera coverage.", "A platform moderates political speech during an election period.", "An insurer uses driving data collected by a partner with unclear consent.", "A public agency receives a model update shortly before a benefits deadline.", "A manufacturer delegates safety classification to a cloud API.", "A retailer wants to use customer conversations for model training.", "A court administrator considers an AI risk score in bail decisions.", "A transport operator introduces an autonomous shuttle on a mixed-traffic route.", "A research lab publishes a model whose training data provenance is incomplete.", "A utility uses a forecast to disconnect loads during a heatwave.", "A lender finds disparate error rates across protected groups.", "A clinic's appeal process cannot explain which data influenced a denial.", "A vendor contract omits incident notification and audit rights.", "A model owner leaves after deployment and no accountable role is assigned.", "A chatbot gives legal guidance without escalation to a qualified professional.", "A biometric system stores raw images longer than its stated purpose.", "A content model generates convincing fabricated emergency announcements.", "A procurement team compares models using only vendor-selected examples.", "A regulator requests a record of training and validation datasets.", "A system's human reviewer routinely rubber-stamps automated decisions.", "A model is used in a country with different discrimination and privacy rules.", "A customer cannot opt out of a high-impact automated decision.", "A supplier claims a general-purpose model is safe because it passed a benchmark.", "A safety case lacks evidence for rare environmental conditions.", "A data steward discovers that consent language excluded secondary AI use.", "A model's failure harms a third party not represented in the service contract.", "An incident report omits near misses because no injury occurred.", "A public dashboard exposes individual-level model scores.", "A system is retired but downstream teams still call its endpoint.", "An audit finds controls exist on paper but are not evidenced in operation."]),
6: ("Operations, monitoring, and lifecycle", [
"A production model's feature distribution changes after a new mobile app release.", "A call-centre model degrades when a holiday campaign changes caller intent.", "A factory model needs a rollback after a firmware update.", "A cloud inference service scales across regions with different hardware.", "A model registry contains two artifacts with the same friendly name.", "A monitoring alert fires because a label feed is delayed, not because accuracy fell.", "A recommendation model's feedback loop changes the population it observes.", "A data pipeline silently drops one country during a scheduled load.", "A model is retrained from a mutable object-store path.", "A safety threshold is changed manually during an incident.", "An edge device operates offline for several days before syncing predictions.", "A provider changes an embedding model without changing the API version.", "A drift detector is calibrated on an unusually stable month.", "A model has no shadow deployment before replacing a legacy service.", "A hospital needs to compare outputs before and after a retraining.", "A fraud model is suspended when the label definition changes.", "A delivery service must investigate degradation in one postcode group.", "An operator needs an abstain response when sensor quality is poor.", "A model consumes a feature whose upstream owner deprecates it.", "A release pipeline promotes a model without a signed approval.", "A chatbot's prompt and retrieval index change independently.", "A model-serving cache returns stale risk scores.", "An inference log contains sensitive payloads and excessive retention.", "A seasonal model is monitored with the wrong baseline.", "A team cannot reproduce a customer-visible prediction from its logs.", "A model is retrained after a drift alert without confirming the cause.", "A vendor's service-level report aggregates away important minority slices.", "An old model remains embedded in a mobile app after server retirement.", "A control chart flags normal variation as a defect.", "A model rollback restores accuracy but loses a required fairness improvement.", "An incident response lacks a named technical and business owner.", "A data contract changes a categorical spelling from 'urban' to 'Urban'.", "A model's explanation service is unavailable while predictions continue.", "A lifecycle review finds no exit criteria for experimental deployment."]),
7: ("Advanced AI systems and integration", [
"A retrieval-augmented clinical assistant quotes a superseded treatment guideline.", "An agent books travel and can spend money through an external tool.", "A multimodal model combines a radiograph with a clinician's free-text note.", "A code assistant suggests a vulnerable dependency version.", "A vision-language robot follows a malicious instruction printed on a box.", "A foundation model is fine-tuned with a small specialist corpus.", "An agent plans a warehouse task but cannot verify whether an action succeeded.", "A synthetic-data generator creates realistic but privacy-sensitive patient records.", "A model routes requests between several specialized experts.", "A generative system's context window truncates the safety policy.", "A tool-using agent retries a payment after an ambiguous network response.", "A multimodal benchmark over-represents clean English captions.", "A model's chain of actions cannot be reconstructed from telemetry.", "A code model memorizes a secret from a repository fixture.", "A retrieval index contains poisoned documents with authoritative wording.", "A foundation model is deployed on a constrained edge accelerator.", "A synthetic image generator distorts minority medical presentations.", "A model evaluator uses another language model as the sole judge.", "An agent's goal conflicts with a hard operational safety constraint.", "A fine-tuned model forgets a previously supported language.", "A multimodal assistant confuses a diagram legend with a data value.", "A generative model produces plausible but impossible engineering dimensions.", "An agent has permission to access more data than its task requires.", "A tool response contains markup that changes the assistant's instructions.", "A model's safety behavior varies between quantized and full-precision versions.", "A benchmark rewards verbosity instead of factual correctness.", "A retrieval system cannot distinguish user-provided claims from trusted sources.", "An autonomous workflow has no approval checkpoint before an irreversible action.", "A model update improves helpfulness but increases hallucinated citations.", "Synthetic labels are used to train a classifier without measuring label realism.", "A foundation model's capability emerges only when tools are enabled.", "An agent's memory stores outdated personal preferences.", "A multimodal system exposes sensitive text through image captions.", "A red-team report identifies a failure that ordinary accuracy metrics miss."]),
}

# Build two different, level-appropriate questions from every concrete case.
QUESTION_BANK = {}
for chapter, (title, contexts) in CHAPTERS.items():
    k2, k3 = [], []
    for n, (case, base) in enumerate(zip(contexts, CASES), start=1):
        concept, domain, situation, focus = base
        k2.append({
            "id": f"C{chapter}-K2-{n:02d}", "level": "K2", "concept": concept,
            "domain": domain,
            "question": f"In {domain}, {case} Explain how this situation illustrates {concept}, and identify the key distinction or quality concern a tester should document.",
            "answer_focus": focus,
        })
        k3.append({
            "id": f"C{chapter}-K3-{n:02d}", "level": "K3", "concept": concept,
            "domain": domain,
            "question": f"You are testing the {domain} system described here: {case} Design a practical test or assurance decision for this case, justify the evidence needed, and state what action follows from a failure. Relate the decision to {concept}.",
            "answer_focus": focus,
        })
    QUESTION_BANK[chapter] = {"title": title, "K2": k2, "K3": k3}


def verify(bank):
    questions = [q["question"] for chapter in bank.values() for level in ("K2", "K3") for q in chapter[level]]
    unique = set(questions)
    print(f"Total questions generated: {len(questions)}")
    print(f"Number of unique questions: {len(unique)}")
    print(f"Number of duplicates: {len(questions) - len(unique)}")
    print("First 10 sample questions:")
    for i, question in enumerate(questions[:10], 1):
        print(f"{i}. {question}")
    assert len(questions) >= 468
    assert len(unique) == len(questions)
    assert all(set(chapter) >= {"title", "K2", "K3"} for chapter in bank.values())


if __name__ == "__main__":
    verify(QUESTION_BANK)
    # Write a plain importable dictionary module in addition to this generator.
    target = Path(__file__).with_name("question_bank.py")
    target.write_text("# Generated by generate_unique_questions.py\nQUESTION_BANK = " + repr(QUESTION_BANK) + "\n", encoding="utf-8")
    print(f"Importable dictionary saved to: {target}")
